<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    public const ROLE_ADMIN = 'admin';
    public const ROLE_MANAGEMENT = 'management';
    public const ROLE_EMPLOYEE = 'employee';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password_hash',
        'role',
        'mfa_secret',
        'mfa_enabled',
        'encryption_key',
        'is_active',
        'daily_rate',
        'overtime_rate',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password_hash',
        'mfa_secret',
        'encryption_key',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password_hash'     => 'hashed',
        'mfa_enabled'       => 'boolean',
        'is_active'         => 'boolean',
        'daily_rate'        => 'float',
        'overtime_rate'     => 'float',
    ];

    /**
     * Check if user has admin role.
     */
    public function isAdmin(): bool
    {
        return $this->role === self::ROLE_ADMIN;
    }

    /**
     * Check if user has management role.
     */
    public function isManagement(): bool
    {
        return $this->role === self::ROLE_MANAGEMENT;
    }

    /**
     * Check if user has employee role.
     */
    public function isEmployee(): bool
    {
        return $this->role === self::ROLE_EMPLOYEE;
    }

    /**
     * Get the password for the user (for authentication).
     */
    public function getAuthPassword(): string
    {
        return $this->password_hash;
    }

    /**
     * Set the password attribute and automatically hash it using bcrypt.
     * Uses cost factor 12 as configured in config/hashing.php
     *
     * @param string $value The plain text password
     * @return void
     */
    public function setPasswordAttribute(string $value): void
    {
        $this->attributes['password_hash'] = Hash::make($value, [
            'rounds' => config('hashing.bcrypt.rounds', 12),
        ]);
    }

    /**
     * Get the user's attendance records.
     */
    public function attendanceRecords(): HasMany
    {
        return $this->hasMany(AttendanceRecord::class);
    }

    /**
     * Get the QR codes generated by this user.
     */
    public function generatedQRCodes(): HasMany
    {
        return $this->hasMany(QRCode::class, 'generated_by');
    }
}
